# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action', '0003_auto_20160409_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='userprofile/default.jpeg', upload_to='userprofile'),
        ),
    ]
