# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='userprofile'),
            preserve_default=False,
        ),
    ]
